

package org.jetbrains.kotlin.compiler.plugin.template.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.compiler.plugin.template.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("koin-compiler-plugin/testData/diagnostics")
@TestDataPath("$PROJECT_ROOT")
public class JvmDiagnosticTestGenerated extends AbstractJvmDiagnosticTest {
  @Test
  public void testAllFilesPresentInDiagnostics() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("koin-compiler-plugin/testData/diagnostics"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("call_site_dsl_dynamic_missing_softened_w003.kt")
  public void testCall_site_dsl_dynamic_missing_softened_w003() {
    runTest("koin-compiler-plugin/testData/diagnostics/call_site_dsl_dynamic_missing_softened_w003.kt");
  }

  @Test
  @TestMetadata("call_site_param_arity_mismatch.kt")
  public void testCall_site_param_arity_mismatch() {
    runTest("koin-compiler-plugin/testData/diagnostics/call_site_param_arity_mismatch.kt");
  }

  @Test
  @TestMetadata("call_site_param_dsl_missing_d006.kt")
  public void testCall_site_param_dsl_missing_d006() {
    runTest("koin-compiler-plugin/testData/diagnostics/call_site_param_dsl_missing_d006.kt");
  }

  @Test
  @TestMetadata("call_site_param_indirect_helper.kt")
  public void testCall_site_param_indirect_helper() {
    runTest("koin-compiler-plugin/testData/diagnostics/call_site_param_indirect_helper.kt");
  }

  @Test
  @TestMetadata("call_site_param_mismatch_no_entry_point.kt")
  public void testCall_site_param_mismatch_no_entry_point() {
    runTest("koin-compiler-plugin/testData/diagnostics/call_site_param_mismatch_no_entry_point.kt");
  }

  @Test
  @TestMetadata("call_site_param_missing_d006.kt")
  public void testCall_site_param_missing_d006() {
    runTest("koin-compiler-plugin/testData/diagnostics/call_site_param_missing_d006.kt");
  }

  @Test
  @TestMetadata("call_site_param_no_injected_no_d006.kt")
  public void testCall_site_param_no_injected_no_d006() {
    runTest("koin-compiler-plugin/testData/diagnostics/call_site_param_no_injected_no_d006.kt");
  }

  @Test
  @TestMetadata("call_site_param_nullable_ok.kt")
  public void testCall_site_param_nullable_ok() {
    runTest("koin-compiler-plugin/testData/diagnostics/call_site_param_nullable_ok.kt");
  }

  @Test
  @TestMetadata("call_site_param_ok.kt")
  public void testCall_site_param_ok() {
    runTest("koin-compiler-plugin/testData/diagnostics/call_site_param_ok.kt");
  }

  @Test
  @TestMetadata("call_site_param_type_mismatch.kt")
  public void testCall_site_param_type_mismatch() {
    runTest("koin-compiler-plugin/testData/diagnostics/call_site_param_type_mismatch.kt");
  }

  @Test
  @TestMetadata("call_site_unreachable_module_d002.kt")
  public void testCall_site_unreachable_module_d002() {
    runTest("koin-compiler-plugin/testData/diagnostics/call_site_unreachable_module_d002.kt");
  }

  @Test
  @TestMetadata("circular_dependency_broken_by_lazy.kt")
  public void testCircular_dependency_broken_by_lazy() {
    runTest("koin-compiler-plugin/testData/diagnostics/circular_dependency_broken_by_lazy.kt");
  }

  @Test
  @TestMetadata("circular_dependency_direct.kt")
  public void testCircular_dependency_direct() {
    runTest("koin-compiler-plugin/testData/diagnostics/circular_dependency_direct.kt");
  }

  @Test
  @TestMetadata("circular_dependency_transitive.kt")
  public void testCircular_dependency_transitive() {
    runTest("koin-compiler-plugin/testData/diagnostics/circular_dependency_transitive.kt");
  }

  @Test
  @TestMetadata("configuration_label_mismatch.kt")
  public void testConfiguration_label_mismatch() {
    runTest("koin-compiler-plugin/testData/diagnostics/configuration_label_mismatch.kt");
  }

  @Test
  @TestMetadata("create_function_missing_dependency_d001.kt")
  public void testCreate_function_missing_dependency_d001() {
    runTest("koin-compiler-plugin/testData/diagnostics/create_function_missing_dependency_d001.kt");
  }

  @Test
  @TestMetadata("cross_module_genuine_missing_d001.kt")
  public void testCross_module_genuine_missing_d001() {
    runTest("koin-compiler-plugin/testData/diagnostics/cross_module_genuine_missing_d001.kt");
  }

  @Test
  @TestMetadata("cross_module_leaf_deferred_w002.kt")
  public void testCross_module_leaf_deferred_w002() {
    runTest("koin-compiler-plugin/testData/diagnostics/cross_module_leaf_deferred_w002.kt");
  }

  @Test
  @TestMetadata("cross_module_scanned_class_koinapp_ok.kt")
  public void testCross_module_scanned_class_koinapp_ok() {
    runTest("koin-compiler-plugin/testData/diagnostics/cross_module_scanned_class_koinapp_ok.kt");
  }

  @Test
  @TestMetadata("cross_module_sibling_koinapp_ok.kt")
  public void testCross_module_sibling_koinapp_ok() {
    runTest("koin-compiler-plugin/testData/diagnostics/cross_module_sibling_koinapp_ok.kt");
  }

  @Test
  @TestMetadata("dsl_bind_chained_and_scoped_d001.kt")
  public void testDsl_bind_chained_and_scoped_d001() {
    runTest("koin-compiler-plugin/testData/diagnostics/dsl_bind_chained_and_scoped_d001.kt");
  }

  @Test
  @TestMetadata("dsl_bind_missing_dependency_d001.kt")
  public void testDsl_bind_missing_dependency_d001() {
    runTest("koin-compiler-plugin/testData/diagnostics/dsl_bind_missing_dependency_d001.kt");
  }

  @Test
  @TestMetadata("dsl_bind_narrowed_dependency_no_false_cycle.kt")
  public void testDsl_bind_narrowed_dependency_no_false_cycle() {
    runTest("koin-compiler-plugin/testData/diagnostics/dsl_bind_narrowed_dependency_no_false_cycle.kt");
  }

  @Test
  @TestMetadata("dsl_bind_opaque_lambda_missing_dependency_d002.kt")
  public void testDsl_bind_opaque_lambda_missing_dependency_d002() {
    runTest("koin-compiler-plugin/testData/diagnostics/dsl_bind_opaque_lambda_missing_dependency_d002.kt");
  }

  @Test
  @TestMetadata("dsl_bind_valid_graph_ok.kt")
  public void testDsl_bind_valid_graph_ok() {
    runTest("koin-compiler-plugin/testData/diagnostics/dsl_bind_valid_graph_ok.kt");
  }

  @Test
  @TestMetadata("dsl_binds_array_missing_dependency_d001.kt")
  public void testDsl_binds_array_missing_dependency_d001() {
    runTest("koin-compiler-plugin/testData/diagnostics/dsl_binds_array_missing_dependency_d001.kt");
  }

  @Test
  @TestMetadata("dsl_binds_array_valid_graph_ok.kt")
  public void testDsl_binds_array_valid_graph_ok() {
    runTest("koin-compiler-plugin/testData/diagnostics/dsl_binds_array_valid_graph_ok.kt");
  }

  @Test
  @TestMetadata("dsl_create_function_bind_no_false_cycle.kt")
  public void testDsl_create_function_bind_no_false_cycle() {
    runTest("koin-compiler-plugin/testData/diagnostics/dsl_create_function_bind_no_false_cycle.kt");
  }

  @Test
  @TestMetadata("dsl_function_module_virtual_dispatch_w003.kt")
  public void testDsl_function_module_virtual_dispatch_w003() {
    runTest("koin-compiler-plugin/testData/diagnostics/dsl_function_module_virtual_dispatch_w003.kt");
  }

  @Test
  @TestMetadata("dsl_hint_name_collision.kt")
  public void testDsl_hint_name_collision() {
    runTest("koin-compiler-plugin/testData/diagnostics/dsl_hint_name_collision.kt");
  }

  @Test
  @TestMetadata("dsl_lambda_body_missing_dependency_d002.kt")
  public void testDsl_lambda_body_missing_dependency_d002() {
    runTest("koin-compiler-plugin/testData/diagnostics/dsl_lambda_body_missing_dependency_d002.kt");
  }

  @Test
  @TestMetadata("dsl_module_array_tolist_precision_d001.kt")
  public void testDsl_module_array_tolist_precision_d001() {
    runTest("koin-compiler-plugin/testData/diagnostics/dsl_module_array_tolist_precision_d001.kt");
  }

  @Test
  @TestMetadata("dsl_module_function_returns_list_precision_d001.kt")
  public void testDsl_module_function_returns_list_precision_d001() {
    runTest("koin-compiler-plugin/testData/diagnostics/dsl_module_function_returns_list_precision_d001.kt");
  }

  @Test
  @TestMetadata("dsl_module_list_plus_precision_d001.kt")
  public void testDsl_module_list_plus_precision_d001() {
    runTest("koin-compiler-plugin/testData/diagnostics/dsl_module_list_plus_precision_d001.kt");
  }

  @Test
  @TestMetadata("dsl_module_listof_precision_d001.kt")
  public void testDsl_module_listof_precision_d001() {
    runTest("koin-compiler-plugin/testData/diagnostics/dsl_module_listof_precision_d001.kt");
  }

  @Test
  @TestMetadata("dsl_module_local_val_precision_d001.kt")
  public void testDsl_module_local_val_precision_d001() {
    runTest("koin-compiler-plugin/testData/diagnostics/dsl_module_local_val_precision_d001.kt");
  }

  @Test
  @TestMetadata("dsl_module_not_loaded.kt")
  public void testDsl_module_not_loaded() {
    runTest("koin-compiler-plugin/testData/diagnostics/dsl_module_not_loaded.kt");
  }

  @Test
  @TestMetadata("dsl_module_unreachable.kt")
  public void testDsl_module_unreachable() {
    runTest("koin-compiler-plugin/testData/diagnostics/dsl_module_unreachable.kt");
  }

  @Test
  @TestMetadata("dsl_new_constructor_missing_dependency_d001.kt")
  public void testDsl_new_constructor_missing_dependency_d001() {
    runTest("koin-compiler-plugin/testData/diagnostics/dsl_new_constructor_missing_dependency_d001.kt");
  }

  @Test
  @TestMetadata("dsl_new_constructor_valid_graph_ok.kt")
  public void testDsl_new_constructor_valid_graph_ok() {
    runTest("koin-compiler-plugin/testData/diagnostics/dsl_new_constructor_valid_graph_ok.kt");
  }

  @Test
  @TestMetadata("dsl_singleof_function_qualifier_ok.kt")
  public void testDsl_singleof_function_qualifier_ok() {
    runTest("koin-compiler-plugin/testData/diagnostics/dsl_singleof_function_qualifier_ok.kt");
  }

  @Test
  @TestMetadata("dsl_singleof_missing_dependency_d001.kt")
  public void testDsl_singleof_missing_dependency_d001() {
    runTest("koin-compiler-plugin/testData/diagnostics/dsl_singleof_missing_dependency_d001.kt");
  }

  @Test
  @TestMetadata("dsl_singleof_named_qualifier_disambiguates_consumer.kt")
  public void testDsl_singleof_named_qualifier_disambiguates_consumer() {
    runTest("koin-compiler-plugin/testData/diagnostics/dsl_singleof_named_qualifier_disambiguates_consumer.kt");
  }

  @Test
  @TestMetadata("dsl_singleof_narrowed_dependency_no_false_cycle.kt")
  public void testDsl_singleof_narrowed_dependency_no_false_cycle() {
    runTest("koin-compiler-plugin/testData/diagnostics/dsl_singleof_narrowed_dependency_no_false_cycle.kt");
  }

  @Test
  @TestMetadata("entry_dsl_dynamic_modules_missing_softened.kt")
  public void testEntry_dsl_dynamic_modules_missing_softened() {
    runTest("koin-compiler-plugin/testData/diagnostics/entry_dsl_dynamic_modules_missing_softened.kt");
  }

  @Test
  @TestMetadata("entry_dynamic_modules_missing.kt")
  public void testEntry_dynamic_modules_missing() {
    runTest("koin-compiler-plugin/testData/diagnostics/entry_dynamic_modules_missing.kt");
  }

  @Test
  @TestMetadata("entry_dynamic_valid_disclosed_w003.kt")
  public void testEntry_dynamic_valid_disclosed_w003() {
    runTest("koin-compiler-plugin/testData/diagnostics/entry_dynamic_valid_disclosed_w003.kt");
  }

  @Test
  @TestMetadata("entry_koinapplication_core_scan_missing.kt")
  public void testEntry_koinapplication_core_scan_missing() {
    runTest("koin-compiler-plugin/testData/diagnostics/entry_koinapplication_core_scan_missing.kt");
  }

  @Test
  @TestMetadata("entry_load_koin_modules_ok.kt")
  public void testEntry_load_koin_modules_ok() {
    runTest("koin-compiler-plugin/testData/diagnostics/entry_load_koin_modules_ok.kt");
  }

  @Test
  @TestMetadata("entry_modules_list_variable_ok.kt")
  public void testEntry_modules_list_variable_ok() {
    runTest("koin-compiler-plugin/testData/diagnostics/entry_modules_list_variable_ok.kt");
  }

  @Test
  @TestMetadata("entry_modules_partial_resolution_w003.kt")
  public void testEntry_modules_partial_resolution_w003() {
    runTest("koin-compiler-plugin/testData/diagnostics/entry_modules_partial_resolution_w003.kt");
  }

  @Test
  @TestMetadata("entry_orphan_module_not_reachable_d001.kt")
  public void testEntry_orphan_module_not_reachable_d001() {
    runTest("koin-compiler-plugin/testData/diagnostics/entry_orphan_module_not_reachable_d001.kt");
  }

  @Test
  @TestMetadata("entry_shared_module_missing_dedup.kt")
  public void testEntry_shared_module_missing_dedup() {
    runTest("koin-compiler-plugin/testData/diagnostics/entry_shared_module_missing_dedup.kt");
  }

  @Test
  @TestMetadata("entry_startkoin_core_scan_crossmodule_ok.kt")
  public void testEntry_startkoin_core_scan_crossmodule_ok() {
    runTest("koin-compiler-plugin/testData/diagnostics/entry_startkoin_core_scan_crossmodule_ok.kt");
  }

  @Test
  @TestMetadata("entry_startkoin_core_scan_missing.kt")
  public void testEntry_startkoin_core_scan_missing() {
    runTest("koin-compiler-plugin/testData/diagnostics/entry_startkoin_core_scan_missing.kt");
  }

  @Test
  @TestMetadata("entry_unreached_incomplete_includes_w001.kt")
  public void testEntry_unreached_incomplete_includes_w001() {
    runTest("koin-compiler-plugin/testData/diagnostics/entry_unreached_incomplete_includes_w001.kt");
  }

  @Test
  @TestMetadata("factory_suspend_fun_interface_d007.kt")
  public void testFactory_suspend_fun_interface_d007() {
    runTest("koin-compiler-plugin/testData/diagnostics/factory_suspend_fun_interface_d007.kt");
  }

  @Test
  @TestMetadata("koin_configuration_dsl_module_instance_a3.kt")
  public void testKoin_configuration_dsl_module_instance_a3() {
    runTest("koin-compiler-plugin/testData/diagnostics/koin_configuration_dsl_module_instance_a3.kt");
  }

  @Test
  @TestMetadata("koin_configuration_modules_a3.kt")
  public void testKoin_configuration_modules_a3() {
    runTest("koin-compiler-plugin/testData/diagnostics/koin_configuration_modules_a3.kt");
  }

  @Test
  @TestMetadata("lazy_missing.kt")
  public void testLazy_missing() {
    runTest("koin-compiler-plugin/testData/diagnostics/lazy_missing.kt");
  }

  @Test
  @TestMetadata("missing_dependency.kt")
  public void testMissing_dependency() {
    runTest("koin-compiler-plugin/testData/diagnostics/missing_dependency.kt");
  }

  @Test
  @TestMetadata("missing_viewmodel_artifact.kt")
  public void testMissing_viewmodel_artifact() {
    runTest("koin-compiler-plugin/testData/diagnostics/missing_viewmodel_artifact.kt");
  }

  @Test
  @TestMetadata("missing_worker_artifact.kt")
  public void testMissing_worker_artifact() {
    runTest("koin-compiler-plugin/testData/diagnostics/missing_worker_artifact.kt");
  }

  @Test
  @TestMetadata("provided_missing.kt")
  public void testProvided_missing() {
    runTest("koin-compiler-plugin/testData/diagnostics/provided_missing.kt");
  }

  @Test
  @TestMetadata("qualifier_mismatch.kt")
  public void testQualifier_mismatch() {
    runTest("koin-compiler-plugin/testData/diagnostics/qualifier_mismatch.kt");
  }

  @Test
  @TestMetadata("scoped_cross_scope.kt")
  public void testScoped_cross_scope() {
    runTest("koin-compiler-plugin/testData/diagnostics/scoped_cross_scope.kt");
  }

  @Test
  @TestMetadata("startkoin_missing.kt")
  public void testStartkoin_missing() {
    runTest("koin-compiler-plugin/testData/diagnostics/startkoin_missing.kt");
  }
}
