package org.koin.compiler.plugin.ir

import org.jetbrains.kotlin.DeprecatedForRemovalCompilerApi
import org.jetbrains.kotlin.backend.common.extensions.IrGenerationExtension
import org.jetbrains.kotlin.backend.common.extensions.IrPluginContext
import org.jetbrains.kotlin.descriptors.DescriptorVisibilities
import org.jetbrains.kotlin.descriptors.Modality
import org.jetbrains.kotlin.descriptors.impl.EmptyPackageFragmentDescriptor
import org.jetbrains.kotlin.fir.backend.FirMetadataSource
import org.jetbrains.kotlin.fir.builder.buildPackageDirective
import org.jetbrains.kotlin.fir.declarations.FirDeclarationOrigin
import org.jetbrains.kotlin.fir.declarations.builder.buildFile
import org.jetbrains.kotlin.incremental.components.ExpectActualTracker
import org.jetbrains.kotlin.incremental.components.LookupTracker
import org.jetbrains.kotlin.ir.UNDEFINED_OFFSET
import org.jetbrains.kotlin.ir.declarations.*
import org.jetbrains.kotlin.ir.declarations.impl.IrFileImpl
import org.jetbrains.kotlin.ir.symbols.IrClassSymbol
import org.jetbrains.kotlin.ir.symbols.impl.IrSimpleFunctionSymbolImpl
import org.jetbrains.kotlin.ir.symbols.impl.IrValueParameterSymbolImpl
import org.jetbrains.kotlin.ir.types.classFqName
import org.jetbrains.kotlin.ir.types.classifierOrNull
import org.jetbrains.kotlin.ir.util.*
import org.jetbrains.kotlin.name.CallableId
import org.jetbrains.kotlin.name.ClassId
import org.jetbrains.kotlin.name.Name
import org.koin.compiler.plugin.KoinPluginConstants
import org.koin.compiler.plugin.KoinPluginLogger
import org.koin.compiler.plugin.ProvidedTypeRegistry
import org.koin.compiler.plugin.fir.KoinModuleFirGenerator
import kotlin.io.path.Path
import kotlin.io.path.absolutePathString

class KoinIrExtension(
    private val lookupTracker: LookupTracker?,
    private val expectActualTracker: ExpectActualTracker
) : IrGenerationExtension {
    override fun generate(moduleFragment: IrModuleFragment, pluginContext: IrPluginContext) {
        KoinPluginLogger.debug { "IR Phase starting for module: ${moduleFragment.name}" }

        // Phase 0: Generate bodies for FIR-generated hint functions and registry function
        // These are generated by KoinModuleFirGenerator in FIR phase
        KoinPluginLogger.debug { "Phase 0: Generating hint function bodies" }
        val hintBodyGenerator = KoinHintTransformer(pluginContext)
        moduleFragment.transform(hintBodyGenerator, null)

        // Shared qualifier extractor and optional safety validator
        val qualifierExtractor = QualifierExtractor(pluginContext)
        val safetyValidator = if (KoinPluginLogger.compileSafetyEnabled) {
            KoinPluginLogger.debug { "Compile safety: ENABLED (skipDefaultValues=${KoinPluginLogger.skipDefaultValuesEnabled})" }
            CompileSafetyValidator(qualifierExtractor)
        } else {
            KoinPluginLogger.debug { "Compile safety: DISABLED" }
            null
        }

        // Phase 1: Process @Module/@ComponentScan/@Singleton/@Factory annotations
        // Generates: fun MyModule.module() = module { single<A>(); factory<B>() }
        KoinPluginLogger.debug { "Phase 1: Processing annotations" }
        val annotationProcessor = KoinAnnotationProcessor(pluginContext, qualifierExtractor, safetyValidator, lookupTracker, expectActualTracker)
        annotationProcessor.collectAnnotations(moduleFragment)
        annotationProcessor.generateModuleExtensions(moduleFragment)

        // Phase 2: Transform single<T>() -> single(T::class, null) { T(get()) }
        // Also collects DSL definitions and pending call-site validations
        KoinPluginLogger.debug { "Phase 2: Transforming DSL calls" }
        val koinTransformer = KoinDSLTransformer(pluginContext, lookupTracker)
        moduleFragment.transform(koinTransformer, null)
        val dslDefinitions = koinTransformer.dslDefinitions
        val pendingCallSites = koinTransformer.collectedCallSites
        KoinPluginLogger.debug { "Phase 2: Collected ${dslDefinitions.size} DSL definitions, ${pendingCallSites.size} pending call sites" }

        // Phase 2.5: Generate DSL definition hints for cross-module discovery
        // Each DSL definition (single<T>, factory<T>, etc.) generates a hint function
        // so downstream modules can discover these definitions via referenceFunctions()
        if (dslDefinitions.isNotEmpty() && KoinPluginLogger.compileSafetyEnabled) {
            KoinPluginLogger.debug { "Phase 2.5: Generating ${dslDefinitions.size} DSL definition hints" }
            generateDslDefinitionHints(pluginContext, moduleFragment, dslDefinitions)
        }

        // Phase 3: Transform startKoin<T> { } to inject modules()
        // Transforms: startKoin<MyApp> { printLogger() }
        // Into: startKoin { printLogger(); modules(listOf(Module1().module, ...)) }
        // A3 full-graph validation includes DSL definitions as providers + consumers
        KoinPluginLogger.debug { "Phase 3: Transforming startKoin calls" }
        val startKoinTransformer = KoinStartTransformer(pluginContext, moduleFragment, annotationProcessor, safetyValidator, lookupTracker, expectActualTracker, dslDefinitions)
        moduleFragment.transform(startKoinTransformer, null)

        // Phase 3.1: DSL-only A3 validation (when startKoin { } is present but no startKoin<T>() / @KoinApplication)
        // Validates constructor parameters of local DSL definitions against all known definitions.
        // This catches missing definitions like commenting out single<Repository>() that a ViewModel needs.
        // Only runs in the entry-point module (the one that calls startKoin { }) to avoid false positives
        // in leaf modules that don't have the full graph visible.
        if (safetyValidator != null && dslDefinitions.isNotEmpty()
            && safetyValidator.assembledGraphTypes.isEmpty()
            && startKoinTransformer.hasKoinEntryPoint) {
            KoinPluginLogger.debug { "Phase 3.1: DSL-only A3 validation (${dslDefinitions.size} local DSL definitions)" }
            validateDslDefinitionGraph(pluginContext, dslDefinitions, annotationProcessor, safetyValidator)
        }

        // Phase 3.5: Validate pending call sites (simple loop, no tree walk)
        // Checks collected call sites against the assembled graph + DSL definitions.
        // Unresolved call sites (when no full graph) generate call-site hints for deferred validation.
        if (safetyValidator != null && pendingCallSites.isNotEmpty()) {
            KoinPluginLogger.debug { "Phase 3.5: Validating ${pendingCallSites.size} call-site resolutions (graph types: ${safetyValidator.assembledGraphTypes.size})" }
            validatePendingCallSites(pluginContext, moduleFragment, pendingCallSites, safetyValidator.assembledGraphTypes, dslDefinitions, annotationProcessor)
        }

        // Phase 3.6: Validate call-site hints from dependency modules against known definitions
        // Call-site hints are generated by feature modules that can't resolve call sites locally.
        // The app module (which sees all definitions) validates them here.
        if (safetyValidator != null && KoinPluginLogger.compileSafetyEnabled) {
            validateCallSiteHintsFromDependencies(pluginContext, safetyValidator.assembledGraphTypes, dslDefinitions, annotationProcessor)
        }

        // Phase 4: Transform @Monitor annotated functions
        // Wraps function bodies with Kotzilla trace calls for performance monitoring
        KoinPluginLogger.debug { "Phase 4: Processing @Monitor annotations" }
        val monitorTransformer = KoinMonitorTransformer(pluginContext)
        moduleFragment.transform(monitorTransformer, null)

        KoinPluginLogger.debug { "IR Phase completed" }
    }
}

/**
 * Generate DSL definition hint functions for cross-module discovery.
 * For each DSL definition (single<T>, factory<T>, etc.), generates a hint function
 * in org.koin.plugin.hints that encodes the provided type.
 *
 * Downstream modules discover these via context.referenceFunctions(dsl_<type>).
 */
@OptIn(DeprecatedForRemovalCompilerApi::class)
private fun generateDslDefinitionHints(
    context: IrPluginContext,
    moduleFragment: IrModuleFragment,
    dslDefinitions: List<Definition.DslDef>
) {
    val hintsPackage = KoinModuleFirGenerator.HINTS_PACKAGE

    for (def in dslDefinitions) {
        val targetClass = def.returnTypeClass
        val targetFqName = targetClass.fqNameWhenAvailable ?: continue
        val targetClassId = ClassId.topLevel(targetFqName)

        val defTypeString = when (def.definitionType) {
            DefinitionType.SINGLE -> KoinPluginConstants.DEF_TYPE_SINGLE
            DefinitionType.FACTORY -> KoinPluginConstants.DEF_TYPE_FACTORY
            DefinitionType.SCOPED -> KoinPluginConstants.DEF_TYPE_SCOPED
            DefinitionType.VIEW_MODEL -> KoinPluginConstants.DEF_TYPE_VIEWMODEL
            DefinitionType.WORKER -> KoinPluginConstants.DEF_TYPE_WORKER
        }
        val hintName = KoinModuleFirGenerator.dslDefinitionHintFunctionName(defTypeString)

        // Build the IR function
        val function = context.irFactory.createSimpleFunction(
            startOffset = UNDEFINED_OFFSET,
            endOffset = UNDEFINED_OFFSET,
            origin = IrDeclarationOrigin.DEFINED,
            name = hintName,
            visibility = DescriptorVisibilities.PUBLIC,
            isInline = false,
            isExpect = false,
            returnType = context.irBuiltIns.unitType,
            modality = Modality.FINAL,
            symbol = IrSimpleFunctionSymbolImpl(),
            isTailrec = false,
            isSuspend = false,
            isOperator = false,
            isInfix = false,
            isExternal = false,
            containerSource = null,
            isFakeOverride = false
        )

        // Add parameter with the target class type (concrete type)
        val params = mutableListOf<IrValueParameter>()
        val contributedParam = context.irFactory.createValueParameter(
            startOffset = UNDEFINED_OFFSET,
            endOffset = UNDEFINED_OFFSET,
            origin = IrDeclarationOrigin.DEFINED,
            name = Name.identifier("contributed"),
            type = targetClass.defaultType,
            isAssignable = false,
            symbol = IrValueParameterSymbolImpl(),
            index = 0,
            varargElementType = null,
            isCrossinline = false,
            isNoinline = false,
            isHidden = false
        )
        contributedParam.parent = function
        params.add(contributedParam)

        // Add binding types as additional parameters
        for ((bindingIndex, binding) in def.bindings.withIndex()) {
            val bindingParam = context.irFactory.createValueParameter(
                startOffset = UNDEFINED_OFFSET,
                endOffset = UNDEFINED_OFFSET,
                origin = IrDeclarationOrigin.DEFINED,
                name = Name.identifier("binding$bindingIndex"),
                type = binding.defaultType,
                isAssignable = false,
                symbol = IrValueParameterSymbolImpl(),
                index = bindingIndex + 1,
                varargElementType = null,
                isCrossinline = false,
                isNoinline = false,
                isHidden = false
            )
            bindingParam.parent = function
            params.add(bindingParam)
        }

        function.valueParameters = params

        // Empty body (stub — hint functions are never called)
        function.body = context.irFactory.createBlockBody(UNDEFINED_OFFSET, UNDEFINED_OFFSET, emptyList())

        // Build deterministic file name
        val fileName = buildDslHintFileName(targetClassId, hintName)

        // Create synthetic FirFile for metadata
        val firModuleData = extractFirModuleData(targetClass)
        if (firModuleData == null) {
            KoinPluginLogger.debug { "  WARN: No FIR module data for ${targetClass.name}, skipping DSL hint" }
            continue
        }

        val firFile = buildFile {
            moduleData = firModuleData
            origin = FirDeclarationOrigin.Synthetic.PluginFile
            packageDirective = buildPackageDirective { packageFqName = hintsPackage }
            name = fileName
        }

        // Create synthetic IrFile
        val sourceFileEntry = try {
            val entry = targetClass.fileEntry
            if (entry.name.contains("/") || entry.name.contains("\\")) entry
            else null
        } catch (_: NotImplementedError) {
            null
        }

        // Use target class file entry if available, otherwise use first file in module
        val basePath = sourceFileEntry?.name
            ?: moduleFragment.files.firstOrNull()?.fileEntry?.name
            ?: "/synthetic"
        val fakeNewPath = Path(basePath).parent.resolve(fileName)

        val hintFile = IrFileImpl(
            fileEntry = NaiveSourceBasedFileEntryImpl(fakeNewPath.absolutePathString()),
            packageFragmentDescriptor = EmptyPackageFragmentDescriptor(
                moduleFragment.descriptor,
                hintsPackage
            ),
            module = moduleFragment
        ).also { it.metadata = FirMetadataSource.File(firFile) }

        moduleFragment.addFile(hintFile)
        hintFile.addChild(function)

        // Register for downstream visibility
        context.metadataDeclarationRegistrar.registerFunctionAsMetadataVisible(function)

        val bindingNames = def.bindings.mapNotNull { it.fqNameWhenAvailable?.shortName()?.asString() }
        val bindingInfo = if (bindingNames.isNotEmpty()) " (bindings: ${bindingNames.joinToString()})" else ""
        KoinPluginLogger.debug { "  Generated DSL hint: $hintName -> ${targetClass.name}$bindingInfo" }
    }
}

/** Extract FIR module data from an IR class's metadata. */
private fun extractFirModuleData(irClass: IrClass): org.jetbrains.kotlin.fir.FirModuleData? {
    return when (val src = irClass.metadata) {
        is FirMetadataSource.Class -> src.fir.moduleData
        is FirMetadataSource.Function -> src.fir.moduleData
        is FirMetadataSource.File -> src.fir.moduleData
        else -> null
    }
}

/** Build a deterministic file name for a DSL hint function. */
private fun buildDslHintFileName(targetClassId: ClassId, hintName: Name): String {
    val parts = sequence {
        yieldAll(targetClassId.packageFqName.pathSegments().map { it.asString() })
        yield(targetClassId.shortClassName.asString())
        yield(hintName.asString())
    }
    val fileName = parts
        .map { segment -> segment.replaceFirstChar { it.uppercaseChar() } }
        .joinToString(separator = "")
        .replaceFirstChar { it.lowercaseChar() }
    return "$fileName.kt"
}

/**
 * Discover DSL definition types from hint functions in dependencies.
 * Queries dsl_single, dsl_factory, etc. hint functions and extracts
 * all provided types (concrete + bindings).
 */
@OptIn(DeprecatedForRemovalCompilerApi::class)
private fun discoverDslDefinitionTypes(context: IrPluginContext): Set<String> {
    val types = mutableSetOf<String>()
    val hintsPackage = KoinModuleFirGenerator.HINTS_PACKAGE

    for (defType in KoinPluginConstants.ALL_DEFINITION_TYPES) {
        val functionName = KoinModuleFirGenerator.dslDefinitionHintFunctionName(defType)
        val hintFunctions = context.referenceFunctions(CallableId(hintsPackage, functionName))

        for (hintFuncSymbol in hintFunctions) {
            val hintFunc = hintFuncSymbol.owner
            for (param in hintFunc.valueParameters) {
                val paramClass = (param.type.classifierOrNull as? IrClassSymbol)?.owner ?: continue
                paramClass.fqNameWhenAvailable?.asString()?.let { types.add(it) }
            }
        }
    }

    if (types.isNotEmpty()) {
        KoinPluginLogger.debug { "  Discovered ${types.size} DSL definition types from dependency hints" }
    }

    return types
}

/**
 * Discover DSL definitions from dependency hints as Definition objects.
 * Returns synthetic DslDef objects that serve as providers in graph validation.
 */
@OptIn(DeprecatedForRemovalCompilerApi::class)
private fun discoverDslDefinitionsFromHints(context: IrPluginContext): List<Definition.DslDef> {
    val definitions = mutableListOf<Definition.DslDef>()
    val hintsPackage = KoinModuleFirGenerator.HINTS_PACKAGE
    val defTypeMapping = mapOf(
        KoinPluginConstants.DEF_TYPE_SINGLE to DefinitionType.SINGLE,
        KoinPluginConstants.DEF_TYPE_FACTORY to DefinitionType.FACTORY,
        KoinPluginConstants.DEF_TYPE_SCOPED to DefinitionType.SCOPED,
        KoinPluginConstants.DEF_TYPE_VIEWMODEL to DefinitionType.VIEW_MODEL,
        KoinPluginConstants.DEF_TYPE_WORKER to DefinitionType.WORKER
    )

    for ((defTypeStr, defType) in defTypeMapping) {
        val functionName = KoinModuleFirGenerator.dslDefinitionHintFunctionName(defTypeStr)
        val hintFunctions = context.referenceFunctions(CallableId(hintsPackage, functionName))

        for (hintFuncSymbol in hintFunctions) {
            val hintFunc = hintFuncSymbol.owner
            val params = hintFunc.valueParameters
            if (params.isEmpty()) continue

            // First param is the concrete type, remaining are bindings
            val targetClass = (params[0].type.classifierOrNull as? IrClassSymbol)?.owner ?: continue
            val bindings = params.drop(1).mapNotNull { param ->
                (param.type.classifierOrNull as? IrClassSymbol)?.owner
            }

            definitions.add(Definition.DslDef(
                irClass = targetClass,
                definitionType = defType,
                bindings = bindings
            ))
        }
    }

    if (definitions.isNotEmpty()) {
        KoinPluginLogger.debug { "  Discovered ${definitions.size} DSL definitions from dependency hints" }
    }

    return definitions
}

/**
 * Phase 3.1: DSL-only A3 validation.
 * Validates constructor parameters of local DSL definitions against all known definitions
 * (local DSL + dependency DSL hints + annotation definitions).
 * This runs when there's no startKoin<T>() / @KoinApplication (which would trigger the full A3).
 */
@OptIn(DeprecatedForRemovalCompilerApi::class)
private fun validateDslDefinitionGraph(
    context: IrPluginContext,
    dslDefinitions: List<Definition.DslDef>,
    annotationProcessor: KoinAnnotationProcessor?,
    safetyValidator: CompileSafetyValidator
) {
    // Collect all known definitions (providers)
    val allDefinitions = mutableListOf<Definition>()

    // Local DSL definitions
    allDefinitions.addAll(dslDefinitions)

    // DSL definitions from dependency hints
    val dependencyDslDefs = discoverDslDefinitionsFromHints(context)
    allDefinitions.addAll(dependencyDslDefs)

    // Annotation definitions (local)
    if (annotationProcessor != null) {
        allDefinitions.addAll(annotationProcessor.getAllKnownDefinitions())
    }

    KoinPluginLogger.debug { "  providers: ${allDefinitions.size} (local DSL=${dslDefinitions.size}, dependency DSL=${dependencyDslDefs.size}, annotations=${allDefinitions.size - dslDefinitions.size - dependencyDslDefs.size})" }

    if (allDefinitions.isEmpty()) return

    // Validate local DSL definitions' constructor parameters against all providers
    val registry = BindingRegistry()
    val qualifierExtractor = safetyValidator.qualifierExtractor
    val parameterAnalyzer = ParameterAnalyzer(qualifierExtractor)
    val errorCount = registry.validateModule(
        "DSL graph",
        allDefinitions,
        parameterAnalyzer,
        qualifierExtractor,
        dslDefinitions // only validate local definitions' parameters
    )

    // Populate assembledGraphTypes so Phase 3.5 knows we have a graph
    for (def in allDefinitions) {
        def.returnTypeClass.fqNameWhenAvailable?.asString()?.let { safetyValidator.addAssembledGraphType(it) }
        for (binding in def.bindings) {
            binding.fqNameWhenAvailable?.asString()?.let { safetyValidator.addAssembledGraphType(it) }
        }
    }

    if (errorCount > 0) {
        KoinPluginLogger.debug { "  -> DONE: $errorCount errors found" }
    } else {
        KoinPluginLogger.debug { "  -> DONE: all dependencies satisfied" }
    }
}

/**
 * A4: Validate pending call-site resolutions against the assembled graph.
 * Simple loop — no tree walk needed.
 *
 * When a call site can't be resolved locally and no full graph is available,
 * a call-site hint is generated instead of an error. The app module (which has
 * the full graph) will discover and validate these hints in Phase 3.6.
 */
@OptIn(DeprecatedForRemovalCompilerApi::class)
private fun validatePendingCallSites(
    context: IrPluginContext,
    moduleFragment: IrModuleFragment,
    callSites: List<PendingCallSiteValidation>,
    assembledGraphTypes: Set<String>,
    dslDefinitions: List<Definition>,
    annotationProcessor: KoinAnnotationProcessor?
) {
    val hasFullGraph = assembledGraphTypes.isNotEmpty()

    // Discover DSL definitions from dependency hints (cross-module DSL discovery)
    val dslHintTypes = if (!hasFullGraph) discoverDslDefinitionTypes(context) else emptySet()

    // Build the set of all known provided types
    val allKnownTypes = buildSet {
        addAll(assembledGraphTypes)
        addAll(dslHintTypes)
        // Add DSL definition types + bindings
        for (def in dslDefinitions) {
            def.returnTypeClass.fqNameWhenAvailable?.asString()?.let { add(it) }
            for (b in def.bindings) { b.fqNameWhenAvailable?.asString()?.let { add(it) } }
        }
        // When no startKoin/koinConfiguration in this compilation unit,
        // fall back to annotation definitions as known types
        if (!hasFullGraph && annotationProcessor != null) {
            for (def in annotationProcessor.getAllKnownDefinitions()) {
                def.returnTypeClass.fqNameWhenAvailable?.asString()?.let { add(it) }
                for (b in def.bindings) { b.fqNameWhenAvailable?.asString()?.let { add(it) } }
            }
        }
    }

    // Also check for definition annotations on the target class (heuristic when no graph)
    val definitionAnnotationFqNames: Set<String> by lazy {
        (org.koin.compiler.plugin.KoinAnnotationFqNames.KOIN_DEFINITION_ANNOTATIONS.map { it.asString() } +
            org.koin.compiler.plugin.KoinAnnotationFqNames.JAKARTA_SINGLETON.asString() +
            org.koin.compiler.plugin.KoinAnnotationFqNames.JAVAX_SINGLETON.asString()).toSet()
    }

    // Collect unresolved call sites for deferred validation via hints
    val unresolvedCallSites = mutableListOf<PendingCallSiteValidation>()

    for (callSite in callSites) {
        // Skip @Provided types
        if (ProvidedTypeRegistry.isProvided(callSite.targetFqName)) {
            KoinPluginLogger.debug { "A4: Skip ${callSite.targetFqName} (@Provided)" }
            continue
        }

        // Skip whitelisted framework types
        if (BindingRegistry.isWhitelistedType(callSite.targetFqName)) {
            KoinPluginLogger.debug { "A4: Skip ${callSite.targetFqName} (framework whitelist)" }
            continue
        }

        // Check assembled graph + DSL definitions + DSL hints
        if (callSite.targetFqName in allKnownTypes) {
            KoinPluginLogger.debug { "A4: OK ${callSite.callFunctionName}<${callSite.targetFqName}>() — found in graph" }
            continue
        }

        // Heuristic: check if the class has a definition annotation (for cross-module scenarios)
        if (!hasFullGraph) {
            val hasAnnotation = callSite.targetClass.annotations.any { annotation ->
                @Suppress("DEPRECATION")
                annotation.type.classFqName?.asString() in definitionAnnotationFqNames
            }
            if (hasAnnotation) {
                KoinPluginLogger.debug { "A4: OK ${callSite.callFunctionName}<${callSite.targetFqName}>() — has definition annotation" }
                continue
            }
        }

        // Not resolved locally
        if (!hasFullGraph) {
            // Defer external types (from dependency JARs) — they may be defined in a downstream module.
            // Local types or modules with local DSL definitions should error immediately.
            val isExternalType = callSite.targetClass.origin == IrDeclarationOrigin.IR_EXTERNAL_DECLARATION_STUB
            if (isExternalType || dslDefinitions.isEmpty()) {
                unresolvedCallSites.add(callSite)
                KoinPluginLogger.debug { "A4: Deferred ${callSite.callFunctionName}<${callSite.targetFqName}>() — will generate call-site hint (external=$isExternalType)" }
                continue
            }
        }

        // Report error — either full graph available, or local type with local definitions
        KoinPluginLogger.error(
            "Missing definition: ${callSite.targetFqName}\n" +
            "  resolved by: ${callSite.callFunctionName}<${callSite.targetClass.name}>()\n" +
            "  No matching definition found in any declared module.\n" +
            "  Check your declaration with Annotation or DSL.",
            callSite.filePath, callSite.line, callSite.column
        )
    }

    // Generate call-site hints for unresolved types (deferred validation)
    if (unresolvedCallSites.isNotEmpty()) {
        KoinPluginLogger.debug { "Phase 3.5: Generating ${unresolvedCallSites.size} call-site hints for deferred validation" }
        generateCallSiteHints(context, moduleFragment, unresolvedCallSites)
    }
}

/**
 * Generate call-site hint functions for deferred cross-module validation.
 * Each unresolved call site type gets a `callsite(required: TargetType)` hint function
 * in org.koin.plugin.hints. The app module discovers and validates these in Phase 3.6.
 */
@OptIn(DeprecatedForRemovalCompilerApi::class)
private fun generateCallSiteHints(
    context: IrPluginContext,
    moduleFragment: IrModuleFragment,
    unresolvedCallSites: List<PendingCallSiteValidation>
) {
    val hintsPackage = KoinModuleFirGenerator.HINTS_PACKAGE
    val hintName = Name.identifier(KoinPluginConstants.CALLSITE_HINT_NAME)

    // Get FIR module data from current module (not from target class which may be external)
    val firModuleData = moduleFragment.files.firstNotNullOfOrNull { file ->
        when (val meta = file.metadata) {
            is FirMetadataSource.File -> meta.fir.moduleData
            is FirMetadataSource.Class -> meta.fir.moduleData
            else -> null
        }
    }
    if (firModuleData == null) {
        KoinPluginLogger.debug { "  WARN: No FIR module data available, skipping call-site hint generation" }
        return
    }

    // Deduplicate by target FQ name
    val uniqueCallSites = unresolvedCallSites.distinctBy { it.targetFqName }

    for (callSite in uniqueCallSites) {
        val targetClass = callSite.targetClass

        // Build the IR function
        val function = context.irFactory.createSimpleFunction(
            startOffset = UNDEFINED_OFFSET,
            endOffset = UNDEFINED_OFFSET,
            origin = IrDeclarationOrigin.DEFINED,
            name = hintName,
            visibility = DescriptorVisibilities.PUBLIC,
            isInline = false,
            isExpect = false,
            returnType = context.irBuiltIns.unitType,
            modality = Modality.FINAL,
            symbol = IrSimpleFunctionSymbolImpl(),
            isTailrec = false,
            isSuspend = false,
            isOperator = false,
            isInfix = false,
            isExternal = false,
            containerSource = null,
            isFakeOverride = false
        )

        // Add parameter with the required type
        val requiredParam = context.irFactory.createValueParameter(
            startOffset = UNDEFINED_OFFSET,
            endOffset = UNDEFINED_OFFSET,
            origin = IrDeclarationOrigin.DEFINED,
            name = Name.identifier("required"),
            type = targetClass.defaultType,
            isAssignable = false,
            symbol = IrValueParameterSymbolImpl(),
            index = 0,
            varargElementType = null,
            isCrossinline = false,
            isNoinline = false,
            isHidden = false
        )
        requiredParam.parent = function
        function.valueParameters = listOf(requiredParam)

        // Empty body (stub — hint functions are never called)
        function.body = context.irFactory.createBlockBody(UNDEFINED_OFFSET, UNDEFINED_OFFSET, emptyList())

        // Build deterministic file name
        val sanitizedName = callSite.targetFqName.split(".")
            .joinToString("") { it.replaceFirstChar { c -> c.uppercaseChar() } }
            .replaceFirstChar { it.lowercaseChar() }
        val fileName = "${sanitizedName}_callsite.kt"

        val firFile = buildFile {
            moduleData = firModuleData
            origin = FirDeclarationOrigin.Synthetic.PluginFile
            packageDirective = buildPackageDirective { packageFqName = hintsPackage }
            name = fileName
        }

        // Create synthetic IrFile
        val basePath = moduleFragment.files.firstOrNull()?.fileEntry?.name ?: "/synthetic"
        val fakeNewPath = Path(basePath).parent.resolve(fileName)

        val hintFile = IrFileImpl(
            fileEntry = NaiveSourceBasedFileEntryImpl(fakeNewPath.absolutePathString()),
            packageFragmentDescriptor = EmptyPackageFragmentDescriptor(
                moduleFragment.descriptor,
                hintsPackage
            ),
            module = moduleFragment
        ).also { it.metadata = FirMetadataSource.File(firFile) }

        moduleFragment.addFile(hintFile)
        hintFile.addChild(function)

        // Register for downstream visibility
        context.metadataDeclarationRegistrar.registerFunctionAsMetadataVisible(function)

        KoinPluginLogger.debug { "  Generated call-site hint: callsite(${callSite.targetFqName})" }
    }
}

/**
 * Phase 3.6: Discover call-site hints from dependency modules and validate them
 * against all known definitions (assembled graph + local DSL + dependency DSL hints).
 *
 * Call-site hints are generated by feature modules that couldn't resolve call sites locally.
 * The module with the full graph (or with all definitions visible) validates them here.
 */
@OptIn(DeprecatedForRemovalCompilerApi::class)
private fun validateCallSiteHintsFromDependencies(
    context: IrPluginContext,
    assembledGraphTypes: Set<String>,
    dslDefinitions: List<Definition>,
    annotationProcessor: KoinAnnotationProcessor?
) {
    val hintsPackage = KoinModuleFirGenerator.HINTS_PACKAGE
    val hintFunctionName = Name.identifier(KoinPluginConstants.CALLSITE_HINT_NAME)

    val hintFunctions = context.referenceFunctions(CallableId(hintsPackage, hintFunctionName))
    if (hintFunctions.isEmpty()) return

    // Build the set of all known provided types
    val allKnownTypes = buildSet {
        addAll(assembledGraphTypes)
        // Add local DSL definitions
        for (def in dslDefinitions) {
            def.returnTypeClass.fqNameWhenAvailable?.asString()?.let { add(it) }
            for (b in def.bindings) { b.fqNameWhenAvailable?.asString()?.let { add(it) } }
        }
        // Add DSL definition hints from dependencies
        addAll(discoverDslDefinitionTypes(context))
        // Add annotation definitions
        if (annotationProcessor != null) {
            for (def in annotationProcessor.getAllKnownDefinitions()) {
                def.returnTypeClass.fqNameWhenAvailable?.asString()?.let { add(it) }
                for (b in def.bindings) { b.fqNameWhenAvailable?.asString()?.let { add(it) } }
            }
        }
    }

    KoinPluginLogger.debug { "Phase 3.6: Validating ${hintFunctions.count()} call-site hints from dependencies (known types: ${allKnownTypes.size})" }

    for (hintFuncSymbol in hintFunctions) {
        val hintFunc = hintFuncSymbol.owner
        val param = hintFunc.valueParameters.firstOrNull() ?: continue
        val targetClass = (param.type.classifierOrNull as? IrClassSymbol)?.owner ?: continue
        val targetFqName = targetClass.fqNameWhenAvailable?.asString() ?: continue

        // Skip @Provided types
        if (ProvidedTypeRegistry.isProvided(targetFqName)) {
            KoinPluginLogger.debug { "A4-deferred: Skip $targetFqName (@Provided)" }
            continue
        }

        // Skip whitelisted framework types
        if (BindingRegistry.isWhitelistedType(targetFqName)) {
            KoinPluginLogger.debug { "A4-deferred: Skip $targetFqName (framework whitelist)" }
            continue
        }

        if (targetFqName in allKnownTypes) {
            KoinPluginLogger.debug { "A4-deferred: OK callsite<$targetFqName> — found in known definitions" }
            continue
        }

        // Report error
        KoinPluginLogger.error(
            "Missing definition: $targetFqName\n" +
            "  Required by a call site in a dependency module (deferred validation).\n" +
            "  No matching definition found in any declared module.\n" +
            "  Check your declaration with Annotation or DSL.",
            null, 0, 0
        )
    }
}
