package org.koin.compiler.plugin.ir

import org.jetbrains.kotlin.backend.common.extensions.IrGenerationExtension
import org.jetbrains.kotlin.backend.common.extensions.IrPluginContext
import org.jetbrains.kotlin.cli.common.messages.MessageCollector
import org.jetbrains.kotlin.incremental.components.ExpectActualTracker
import org.jetbrains.kotlin.incremental.components.LookupTracker
import org.jetbrains.kotlin.ir.declarations.IrModuleFragment
import org.koin.compiler.plugin.KoinPluginLogger

class KoinIrExtension(
    private val lookupTracker: LookupTracker?,
    private val expectActualTracker: ExpectActualTracker,
    // Captured at construction so the trailing CTA always writes to this compilation's
    // collector, even if a parallel compilation in the same Gradle daemon has overwritten
    // the singleton's collector reference by the time we flush.
    private val messageCollector: MessageCollector,
    // Captured at construction (same reason as messageCollector): the compilation's config
    // flags, re-bound onto the IR-phase thread below. Without this, IR-phase reads of
    // compileSafety / skipDefaultValues fell through to the shared global on pool workers
    // (KTZ-4414 flakiness).
    private val flagsHandle: Any,
) : IrGenerationExtension {
    override fun generate(moduleFragment: IrModuleFragment, pluginContext: IrPluginContext) {
        // Re-anchor the per-thread collector AND config flags on this compilation's captured
        // values. Necessary because `KoinPluginLogger.init()` ran on the thread that called
        // `registerExtensions`, which may differ from the thread running IR generation in
        // parallel-daemon mode. `InheritableThreadLocal` inherits only at thread creation —
        // pool workers picked up later won't see init()'s values and would fall through to the
        // shared singletons a parallel compilation may have overwritten.
        KoinPluginLogger.bindThreadCollector(messageCollector)
        KoinPluginLogger.bindThreadFlags(flagsHandle)
        try {
            generateInternal(moduleFragment, pluginContext)
        } finally {
            KoinPluginLogger.unbindThreadFlags()
            KoinPluginLogger.unbindThreadCollector()
        }
    }

    private fun generateInternal(moduleFragment: IrModuleFragment, pluginContext: IrPluginContext) {
        KoinPluginLogger.debug { "IR Phase starting for module: ${moduleFragment.name}" }

        // Phase 0: Generate bodies for FIR-generated hint functions and registry function
        // These are generated by KoinModuleFirGenerator in FIR phase
        KoinPluginLogger.debug { "Phase 0: Generating hint function bodies" }
        val hintBodyGenerator = KoinHintTransformer(pluginContext)
        moduleFragment.transform(hintBodyGenerator, null)

        // Shared qualifier extractor and optional safety validator
        val qualifierExtractor = QualifierExtractor(pluginContext)
        val safetyValidator = if (KoinPluginLogger.compileSafetyEnabled) {
            KoinPluginLogger.debug { "Compile safety: ENABLED (skipDefaultValues=${KoinPluginLogger.skipDefaultValuesEnabled})" }
            CompileSafetyValidator(qualifierExtractor)
        } else {
            KoinPluginLogger.debug { "Compile safety: DISABLED" }
            null
        }

        // Phase 1: Process @Module/@ComponentScan/@Singleton/@Factory annotations
        // Generates: fun MyModule.module() = module { single<A>(); factory<B>() }
        KoinPluginLogger.debug { "Phase 1: Processing annotations" }
        val annotationProcessor = KoinAnnotationProcessor(pluginContext, qualifierExtractor, lookupTracker, expectActualTracker)
        annotationProcessor.collectAnnotations(moduleFragment)
        annotationProcessor.generateModuleExtensions(moduleFragment)

        // Phase 2: Transform single<T>() -> single(T::class, null) { T(get()) }
        // Also collects DSL definitions and pending call-site validations
        KoinPluginLogger.debug { "Phase 2: Transforming DSL calls" }
        val koinTransformer = KoinDSLTransformer(pluginContext, lookupTracker, expectActualTracker)
        moduleFragment.transform(koinTransformer, null)
        val dslDefinitions = koinTransformer.dslDefinitions
        val pendingCallSites = koinTransformer.collectedCallSites
        KoinPluginLogger.debug { "Phase 2: Collected ${dslDefinitions.size} DSL definitions, ${pendingCallSites.size} pending call sites" }

        // Instantiate extracted helper classes
        val dslHintGenerator = DslHintGenerator(pluginContext, ParameterAnalyzer(qualifierExtractor))
        val callSiteValidator = CallSiteValidator(pluginContext)
        val injectedParamHints = InjectedParamHintGenerator(pluginContext, qualifierExtractor)

        // Phase 2.5: Generate DSL definition hints for cross-module discovery
        // Each DSL definition (single<T>, factory<T>, etc.) generates a hint function
        // so downstream modules can discover these definitions via referenceFunctions()
        // Definitions are not the only reason to run. A module that only relays
        // (`module { includes(…) }`) has topology to export, and a named module that now contributes
        // nothing still needs its file rewritten so the previous compile's class cannot linger (see
        // the keep-alive marker in DslHintGenerator). Definitions stay in the condition because an
        // inline `modules(module { … })` has no val at all — allModuleIds is empty there.
        if ((dslDefinitions.isNotEmpty()
                || koinTransformer.moduleIncludes.isNotEmpty()
                || koinTransformer.allModuleIds.isNotEmpty())
            && KoinPluginLogger.compileSafetyEnabled) {
            KoinPluginLogger.debug {
                "Phase 2.5: Generating ${dslDefinitions.size} DSL definition hints" +
                    " + ${koinTransformer.moduleIncludes.size} includes-edge hint(s)"
            }
            dslHintGenerator.generateDslDefinitionHints(
                moduleFragment, dslDefinitions, koinTransformer.moduleIncludes, koinTransformer.allModuleIds,
                koinTransformer.modulesWithIncompleteIncludes
            )
            // Relay classpath-invisible includes() targets' own DSL definition hints through THIS
            // module's output — otherwise a provider 2+ implementation hops away is never on a
            // downstream reader's classpath, no matter how many includes() edges it walks. See
            // relayIncludedDefinitionHints's kdoc.
            dslHintGenerator.relayIncludedDefinitionHints(
                moduleFragment, koinTransformer.moduleIncludes, koinTransformer.allModuleIds
            )
        }

        // Phase 2.6: Generate `@InjectedParam` shape hints for cross-module call-site validation.
        // Each definition with ≥ 1 `@InjectedParam` slot emits an `injectedparams_<flat-fqn>(...)`
        // function whose signature mirrors the slot list. Consumer modules read those signatures
        // to enforce parametersOf(...) shape at call sites (KOIN-D005/D006).
        if (KoinPluginLogger.compileSafetyEnabled) {
            val allDefs = mutableListOf<Definition>().apply {
                addAll(dslDefinitions)
                addAll(annotationProcessor.getAllKnownDefinitions())
            }
            if (allDefs.isNotEmpty()) {
                KoinPluginLogger.debug { "Phase 2.6: Indexing @InjectedParam shape across ${allDefs.size} definition(s)" }
                injectedParamHints.generateAndIndexHints(moduleFragment, allDefs)
            }
        }

        // Phase 3: Transform startKoin<T> { } to inject modules()
        // Transforms: startKoin<MyApp> { printLogger() }
        // Into: startKoin { printLogger(); modules(listOf(Module1().module, ...)) }
        // A3 full-graph validation includes DSL definitions as providers + consumers
        KoinPluginLogger.debug { "Phase 3: Transforming startKoin calls" }
        val startKoinTransformer = KoinStartTransformer(pluginContext, moduleFragment, annotationProcessor, safetyValidator, lookupTracker, expectActualTracker, dslDefinitions)
        moduleFragment.transform(startKoinTransformer, null)

        // A3 §4: single graph-verification pass over the reified entry points. Must run before
        // Phase 3.1 so it populates assembledGraphTypes first — Phase 3.1 skips when that set is
        // non-empty, exactly as when validation happened inline during the transform.
        startKoinTransformer.verifyEntryPoints()

        // Phase 3.1: DSL-only A3 validation (when startKoin { } is present but no startKoin<T>() / @KoinApplication)
        // Validates constructor parameters of local DSL definitions against all known definitions.
        // This catches missing definitions like commenting out single<Repository>() that a ViewModel needs.
        // Only runs in the entry-point module (the one that calls startKoin { }) to avoid false positives
        // in leaf modules that don't have the full graph visible.
        if (safetyValidator != null && dslDefinitions.isNotEmpty()
            && safetyValidator.assembledGraphTypes.isEmpty()
            && startKoinTransformer.hasKoinEntryPoint) {
            KoinPluginLogger.debug { "Phase 3.1: DSL-only A3 validation (${dslDefinitions.size} local DSL definitions)" }
            callSiteValidator.validateDslDefinitionGraph(
                dslDefinitions, annotationProcessor, safetyValidator, dslHintGenerator,
                koinTransformer.startKoinModules, koinTransformer.moduleIncludes,
                entryModulesIncomplete = koinTransformer.entryModulesIncomplete,
                entryModulesIncompleteOrigin = koinTransformer.entryModulesIncompleteOrigin,
                modulesWithIncompleteIncludes = koinTransformer.modulesWithIncompleteIncludes,
                ownsAuthoritativeGraph = startKoinTransformer.ownsAuthoritativeGraph
            )
        }

        // Phase 3.5: Validate pending call sites (simple loop, no tree walk)
        // Checks collected call sites against the assembled graph + DSL definitions.
        // Unresolved call sites (when no full graph, OR no Koin entry point at all in this
        // compilation) generate call-site hints for deferred validation instead of hard-erroring —
        // KOIN-D002 requires an assembled graph to judge against (see CompileSafetyValidator's
        // class doc: no entry point ⇒ generation only, never verification). The D005/D006
        // parametersOf shape check is NOT graph-dependent (constructor-derived), so it still runs
        // on every call site regardless — including the deferred ones — inside the function below.
        if (safetyValidator != null && pendingCallSites.isNotEmpty()) {
            KoinPluginLogger.debug { "Phase 3.5: Validating ${pendingCallSites.size} call-site resolutions (graph types: ${safetyValidator.assembledGraphTypes.size})" }
            callSiteValidator.validatePendingCallSites(
                moduleFragment, pendingCallSites, safetyValidator.assembledGraphTypes, dslDefinitions,
                annotationProcessor, dslHintGenerator, injectedParamHints, startKoinTransformer.hasKoinEntryPoint,
            )
        }

        // Phase 3.6: Validate call-site hints from dependency modules against known definitions.
        // Call-site hints are generated by feature modules that can't resolve call sites locally.
        // The app module (which sees all definitions via @KoinApplication) validates them here — and
        // that framing is the gate: this pass judges OTHER modules' deferred resolutions, so it is
        // only licensed where this compilation owns the authoritative application graph.
        //
        // Hence ownsAuthoritativeGraph, not hasKoinEntryPoint. `koinApplication { }` is a real entry
        // point launching an isolated context, and its own graph IS validated (Phase 3.1) — but it is
        // exactly the idiom used for deliberately partial graphs (Compose previews, test fixtures,
        // KMP helpers). Gating here on "any entry point" made every library module containing one
        // hard-error KOIN-D003 for types it neither owns nor should provide.
        //
        // Without an authoritative graph, library modules would produce false positives because they
        // don't have visibility into all modules. With one, we MUST validate even with an empty local
        // graph — otherwise missing Gradle dependencies (e.g. forgetting :data) go undetected.
        if (safetyValidator != null && KoinPluginLogger.compileSafetyEnabled
            && startKoinTransformer.ownsAuthoritativeGraph) {
            callSiteValidator.validateCallSiteHintsFromDependencies(safetyValidator.assembledGraphTypes, dslDefinitions, annotationProcessor, dslHintGenerator)
        }

        // Disclosure: no Koin entry point anywhere in this compilation means compile-safety
        // validation never ran on it — generation only (see CompileSafetyValidator's class doc).
        // Silent is worse than broken, so this is disclosed even though it's not a diagnostic:
        // `warn()` is unconditional (not gated behind userLogs) and respects the informational
        // severity setting (default WARNING, downgradable to INFO under allWarningsAsErrors) —
        // NOT a plain WARNING-severity KoinDiagnostic, which would fire on every library module
        // and recreate #73. Gated on having something to disclose about (this module actually
        // carries Koin definitions), so a module with no Koin usage at all stays silent.
        if (safetyValidator != null && !startKoinTransformer.hasKoinEntryPoint) {
            val hasAnyDefinitions = dslDefinitions.isNotEmpty() || annotationProcessor.getAllKnownDefinitions().isNotEmpty()
            if (hasAnyDefinitions) {
                KoinPluginLogger.warn("compile-safety validation skipped — no Koin entry point in this compilation.")
            }
        }

        // Phase 4: Transform @Monitor annotated functions
        // Wraps function bodies with Kotzilla trace calls for performance monitoring
        KoinPluginLogger.debug { "Phase 4: Processing @Monitor annotations" }
        val monitorTransformer = KoinMonitorTransformer(pluginContext)
        moduleFragment.transform(monitorTransformer, null)
        monitorTransformer.logSummary()

        // Final: emit one AI-assist CTA at the tail of the log if any Koin diagnostic fired.
        // Pass our captured collector to dodge the parallel-daemon singleton race.
        KoinPluginLogger.flushAiAssistCta(messageCollector)

        KoinPluginLogger.debug { "IR Phase completed" }
    }
}
